version: '3.8'

services:
  app:
    build: .
    container_name: app-container
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./src:/app/src
