version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=production
    container_name: app-container
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./server/index.js:/app/server/index.js
      - ./server/src:/app/server/src
      - ./client/src:/app/client/src
